// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftuxwwpkqgtkqccibrbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dXh3d3BrcWd0a3FjY2licmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDY1NDgsImV4cCI6MjA2NTQ4MjU0OH0.nLzWswXdZbsF_aPV4tB2p01rv5gGn27wNUPIpxOR_Po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);